name: PR Validation

on:
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Setup Conan Client
        uses: conan-io/setup-conan@v1.2.0
        with:
          use_venv: true

      - name: Install Conan dependencies
        run: conan install . --build=missing

      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          cxx-compiler: g++
          c-compiler: gcc

      - name: Test Project
        uses: threeal/ctest-action@v1.1.0
